#!/bin/zsh
#
# allDates: List a bunch of file info (mainly for getting all the dates).
#
# Steve DeRose, 2017-11-01
#

# Make a list of Mac OSX spotlight/mdls keywords
#

DATEITEMS=$(cat <<HERE
kMDItemContentCreationDate
kMDItemContentModificationDate
kMDItemDateAdded
kMDItemFSContentChangeDate
kMDItemFSCreationDate
HERE
)

OTHERITEMS=$(cat <<HERE
kMDItemContentType
kMDItemContentTypeTree
kMDItemDisplayName
kMDItemFSCreatorCode
kMDItemFSFinderFlags
kMDItemFSHasCustomIcon
kMDItemFSInvisible
kMDItemFSIsExtensionHidden
kMDItemFSIsStationery
kMDItemFSLabel
kMDItemFSName
kMDItemFSNodeCount
kMDItemFSOwnerGroupID
kMDItemFSOwnerUserID
kMDItemFSSize
kMDItemFSTypeCode
kMDItemKind
kMDItemLogicalSize
kMDItemPhysicalSize
HERE
)

#echo $ITEMS

ITEMS="$DATEITEMS"

while [[ "$#" > 0 ]]; do case $1 in
    -h)
       echo "Bash script to show Mac mdls info on a file."
       echo "    -v List lots of items, not just date ones."
       exit;;
    -v)
       ITEMS="$ITEMS$OTHERITEMS";;
    *) break;;
  esac; shift;
done


if ! [ -e "$1" ]; then
    echo "Cannot find file '$1'."
    exit
fi

stat -f "Created:   %Sc %nModified:  %Sm %nAccessed:  %Sa %nInode cr:  %SB" "$1"
for x in $ITEMS; do
    #echo $x;
    mdls --name "$x" "$1" | tr '=' '\t' | expand -t 40
    #echo
done



