#!/usr/bin/perl -w
#
# Congratulate the user sort of personally.
#
# 2006-02-??: Written by Steven J. DeRose.
# 2010-09-14 sjd: Clean up.
#
use strict;

if ($ARGV[0] && $ARGV[0] =~ /^-h/) {
	system "perldoc $0";
    exit;
}

my $fingerLine = `finger -s $ENV{USER} | tail -n 1`;
chomp($fingerLine);
$fingerLine =~ s/[^ ]* +//;
$fingerLine =~ s/ .*//;
print "\nCongratulations, $fingerLine.\n";

exit;



###############################################################################
###############################################################################
###############################################################################
#

=pod

=head1 Usage

congrats

Look up the user's first name, and congratulate them.



=head1 Ownership

This work by Steven J. DeRose is licensed under a Creative Commons
Attribution-Share Alike 3.0 Unported License. For further information on
this license, see L<http://creativecommons.org/licenses/by-sa/3.0/>.

For the most recent version, see L<http://www.derose.net/steve/utilities/>.

=cut
