#!/bin/bash

if isHelpOption "$1"; then
    echo "isrunning PROG: check whether 'ps -e' shows PROG running."
    echo "    See also 'runonce' and 'ps -C [cmd]'."
    exit
fi

ps -e | grep -i --color=auto --exclude-dir='.svn' -qP " $*\.?\$" 2> /dev/null
if [[ "$?" == "0" ]]; then
    echo "$* IS running."
    exit 1
fi
echo "$* is NOT running."
exit 0

