#!/bin/bash --login
#
# Use 'openall' to start up your preferred set of applications
# Add to Applications menu via Applications/Other/Main_Menu
#
TGT="/tmp/openall.log"

echo "### Starting at " `date` >>$TGT
echo "### PATH: $PATH" >>$TGT

if ! [ -x runonce ]; then
    echo "Can't find executable 'runonce'" >>$TGT
fi

echo "Opening term 1" >>$TGT
gnome-terminal --window-with-profile=blueBG &

echo "Opening term 2" >>$TGT
gnome-terminal  >>$TGT &

echo "Opening Thunderbird" >>$TGT
runonce thunderbird  >>$TGT &

echo "Opening firefox" >>$TGT
runonce firefox >>$TGT &

echo "Opening pidgin" >>$TGT
runonce pidgin  >>$TGT &

echo "Opening autocutsel" >>$TGT
runonce autocutsel  >>$TGT &

echo "Opening glipper" >>$TGT
runonce glipper >>$TGT &
